### ISSUE TITLE
Translation not working | strings.js from strings.po file?

### ISSUE THREAD

**Issue by vyrus0139** [doublespeakgames/adarkroom#706]
tl;dr How do I generate the strings.js from my strings.po file?

Hi, 
I am trying to add a translation. I correctly created the strings.po file. However, I can't generate the strings.js. When I try to run `./tools/po2js.py lang/<YOUR LANG>/strings.po` on my file I get the errors shown below. How can I fix this?  This is my first time posting on github and I've spent many hours on this trying to figure it out. Any help would be appreciated. Thanks!

```
Microsoft Windows [Version 10.0.19045.2604]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>C:\Users\Vyrus0139\adarkroom\tools\po2js.py lang\cs\strings.po
INFO: converting lang\cs\strings.po to lang\cs\strings.js
Traceback (most recent call last):
  File "C:\Users\Vyrus0139\adarkroom\tools\po2js.py", line 33, in <module>
    po = polib.pofile(srcfile, autodetect_encoding=False,
  File "C:\Python39\lib\site-packages\polib.py", line 130, in pofile
    return _pofile_or_mofile(pofile, 'pofile', **kwargs)
  File "C:\Python39\lib\site-packages\polib.py", line 78, in _pofile_or_mofile
    instance = parser.parse()
  File "C:\Python39\lib\site-packages\polib.py", line 1456, in parse
    raise IOError('Syntax error in po file %s(line %s)' %
OSError: Syntax error in po file (line 1)

C:\WINDOWS\system32>
```
![Capture](https://user-images.githubusercontent.com/10591359/224530920-c20b5f53-689a-46bd-b8aa-8ecb4bfacd12.PNG)

**Comment by vyrus0139** [comment]
A simple mistake. Follow the instructions as written. You must first navigate to the directory before executing the command. 

> Create JS
> Now that the strings.po file is translated (don't forget to save it!), you can generate the strings.js that will be used by the game.
> 
> Open a terminal
> cd adarkroom
> ./tools/po2js.py lang/<YOUR LANG>/strings.po
> These steps will create a brand new strings.js, based on the content of the strings.po file.
